### ISSUE TITLE
Removing styling on close button

### ISSUE THREAD

**Issue by indigodavid** [GiuseppeTG/TVmaze#42]
## Great job with your project 👏##

@learnwithalfred and @GiuseppeTG, your work looks amazing, you have developed a great project. In the peer-to-peer code review you told us that you wanted to change the shadow you had on your close button, but you couldn't find how was that property being applied. For you to change that you need to change the focus pseudo-element for your close button. Hope this helps you guys.

Cheers and Happy Coding 👏!!

**Comment by GiuseppeTG** [comment]
Hey @indigodavid 👋 
Thank you for your feedback, very helpful.
Now I was able to show that button just as I wanted, thanks!
